import { ClientCookiesProvider } from "@components/CookiesProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { cookies } from "next/headers";
import LayoutWrapper from "./LayoutWrapper";
const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={sans.className}>
        <ClientCookiesProvider value={cookies().getAll()}>
          <LayoutWrapper>{children}</LayoutWrapper>
        </ClientCookiesProvider>
      </body>
    </html>
  );
}
